name: Android CI (Debug APK)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-35" "build-tools;35.0.0"
          yes | sdkmanager --licenses

      - name: Unzip project
        run: unzip -o UltraMaxLite-Android-Fixed.zip

      - name: Generate Gradle Wrapper (8.7)
        working-directory: UltraMaxLite-Android-Starter
        run: |
          gradle wrapper --gradle-version 8.7
          ./gradlew --version

      - name: Build Debug
        working-directory: UltraMaxLite-Android-Starter
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: UltraMaxLite-debug
          path: UltraMaxLite-Android-Starter/app/build/outputs/apk/debug/*.apk
